# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppleMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppleMusic

  target 'AppleMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppleMusicUITests' do
    # Pods for testing
  end

end
